# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hammertime"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0")
  s.authors = ["Avdi Grimm"]
  s.date = "2024-03-19"
  s.description = "When this library is required, it replaces the default Ruby exception-raising\nbehavior.  When an error is raised, the developer is presented with a menu\nenabling them to ignore the error, view a stack trace, debug the error using IRB\nor ruby-debug, and more.\n"
  s.email = "avdi@avdi.org"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example.rb",
    "examples/loaderror.rb",
    "hammertime.gemspec",
    "lib/hammertime.rb",
    "spec/hammertime_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/avdi/hammertime"
  s.require_paths = ["lib"]
  s.summary = "Exception debugging console for Ruby"

  s.add_runtime_dependency "highline", "~> 2.0"
  s.add_runtime_dependency "debug", "~> 1.8"
  
  s.add_development_dependency "rspec", "~> 3.12"
  s.add_development_dependency "rake", "~> 13.0"
  s.add_development_dependency "rdoc", "~> 6.6"
  s.add_development_dependency "rubocop", "~> 1.62"
  s.add_development_dependency "rubocop-rspec", "~> 2.27"
  s.add_development_dependency "simplecov", "~> 0.22.0"
end

